---
title: "Non Graded Assignment"
output:
  html_notebook: default
  html_document: default
---
Group Members:
Atish Majumdar
Prasanna Natarajan
Vishal Guaba


Creating the table and writing it to a csv file for question1
```{r}
StudentID <- 1410110001:1410111000
DepartmentID <- rep(1:10,100)
CGPA <- runif(1000,4,10)
inp <- cbind(StudentID,DepartmentID,CGPA)
write.csv(inp,"input.csv")
```

Reading from the csv file and finding the solution to question 1
```{r}
data <- read.csv("input.csv")
```
1.a
```{r}
percentageGreaterThan7.5 <- nrow(data[data$CGPA>7.5,])/nrow(data) *100
print(percentageGreaterThan7.5)

```
1.b
```{r}
percentageBet7.5and8.5 <- print(nrow(data[(data$CGPA-7.5) * (8.5-data$CGPA)>0,])/nrow(data) *100)
```
1.c
```{r}
DepID <- 2
d1<-(data[data$DepartmentID == DepID,])
mean(d1[["CGPA"]])
```
1.d
```{r}
d1[sample(1:nrow(d1),runif(1,min = 0, max = nrow(d1))),"CGPA"] <- NA
# without na.rm 
mean(d1[["CGPA"]])
# with na.rm
mean(d1[["CGPA"]],na.rm = T)
```
1.f
```{r}
plot(data$CGPA)
```
2
```{r}
## used data.frame(),data.matrix() , read.table( ), read.csv(),lapply( ), sapply( ), tapply( ), mapply( ), split( )
## Not sure what the deliverable will be
```

3. Reading from a PDF
```{r}
library(tm)
files <- list.files(pattern = "pdf$")
Rpdf <- readPDF(control = list(text = "-layout"))
corpus <- VCorpus(URISource(files[1]), 
      readerControl = list(reader = Rpdf))
corpus.array <- content(content(corpus)[[1]]) ## Store each line in an array
textFreq <- slam::row_sums(TermDocumentMatrix(corpus))
df <- as.data.frame(as.table(textFreq))
```
3.1
```{r}
df
df[which.min(df[,2])]
```


